services:
  user-service:
    build:
      context: ./LMS/backend/user-service
    container_name: user-service
    env_file: .env
    depends_on:
      - user_service_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_db:5432/${USER_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - microservice-network

  user_service_db:
    image: postgres:17-alpine
    container_name: user_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${USER_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 30s
    volumes:
      - user_service_data:/var/lib/postgresql/data
    networks:
      - microservice-network

  course-service:
    build:
      context: ./LMS/backend/course-service
    container_name: course-service
    env_file: .env
    depends_on:
      - course_service_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://course_db:5432/${COURSE_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8082:8082"
    networks:
      - microservice-network

  course_service_db:
    image: postgres:17-alpine
    container_name: course_db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=${COURSE_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 30s
    volumes:
      - course_service_data:/var/lib/postgresql/data
    networks:
      - microservice-network

  minio:
     image: minio/minio:latest
     container_name: minio
     environment:
       - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
       - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
     command: server /minio --console-address :9090
     ports:
       - '9090:9090'
       - '9000:9000'
     volumes:
       - minio-data:/minio
     networks:
       - microservice-network

  api-gateway:
    build:
      context: ./LMS/backend/api-gateway
    container_name: api-gateway
    env_file: .env
    environment:
      - SPRING_CLOUD_GATEWAY_ROUTES_0_URI=http://user-service:8081
      - SPRING_CLOUD_GATEWAY_ROUTES_1_URI=http://course-service:8082
    depends_on:
      - user-service
      - course-service
    ports:
      - '8080:8080'
    networks:
      - microservice-network

  frontend:
    container_name: react_frontend
    build:
      context: ./LMS/frontend/react-app
    volumes:
      - ./LMS/frontend/react-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  course_service_data:
    driver: local
  user_service_data:
    driver: local
  minio-data:
    driver: local
